services:
  - type: web
    name: greencart-backend
    runtime: node
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production 
